# Generated by Django 4.2.19 on 2025-03-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalServiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Service')),
                ('protocol', models.CharField(max_length=255, verbose_name='Protocol')),
                ('request_repr', models.TextField(blank=True, default='', verbose_name='Request representation')),
                ('response_repr', models.TextField(blank=True, default='', verbose_name='Response representation')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('execution_time', models.FloatField(help_text='Time taken in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date time')),
                ('user_id', models.CharField(blank=True, default='', help_text='String version of the user pk', max_length=255, verbose_name='User PK as string')),
            ],
            options={
                'verbose_name': 'external client event',
                'verbose_name_plural': 'external client events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='crudevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='crudevent',
            name='user_pk_as_string',
        ),
        migrations.RemoveField(
            model_name='loginevent',
            name='user',
        ),
        migrations.AddField(
            model_name='crudevent',
            name='user_id',
            field=models.CharField(blank=True, default='', help_text='String version of the user pk', max_length=255, verbose_name='User PK as string'),
        ),
        migrations.AddField(
            model_name='loginevent',
            name='user_id',
            field=models.CharField(blank=True, default='', help_text='String version of the user pk', max_length=255, verbose_name='User PK as string'),
        ),
    ]
