# Generated by Django 4.2.11 on 2025-03-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyaudit', '0004_auto_20170620_1354_squashed_0019_alter_crudevent_changed_fields_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crudevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'CRUD event', 'verbose_name_plural': 'CRUD events'},
        ),
        migrations.AlterModelOptions(
            name='loginevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'login event', 'verbose_name_plural': 'login events'},
        ),
        migrations.AlterModelOptions(
            name='requestevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'request event', 'verbose_name_plural': 'request events'},
        ),
        migrations.RemoveIndex(
            model_name='crudevent',
            name='easyaudit_c_object__82020b_idx',
        ),
        migrations.RenameField(
            model_name='crudevent',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='loginevent',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='requestevent',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='crudevent',
            name='content_type',
        ),
        migrations.AddIndex(
            model_name='crudevent',
            index=models.Index(fields=['object_id'], name='easyaudit_c_object__a12edd_idx'),
        ),
    ]
