# Generated by Django 4.2.11 on 2025-03-04 16:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigIntModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='test data', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='test data', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UUIDModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='test data', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UUIDM2MModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('test_m2m', models.ManyToManyField(to='test_app.uuidmodel')),
            ],
        ),
        migrations.CreateModel(
            name='UUIDForeignKeyModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('test_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.uuidmodel')),
            ],
        ),
        migrations.CreateModel(
            name='M2MModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('test_m2m', models.ManyToManyField(to='test_app.model')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignKeyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('test_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.model')),
            ],
        ),
        migrations.CreateModel(
            name='BigIntM2MModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('test_m2m', models.ManyToManyField(to='test_app.bigintmodel')),
            ],
        ),
        migrations.CreateModel(
            name='BigIntForeignKeyModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('test_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.bigintmodel')),
            ],
        ),
    ]
